// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: obfuscated.proto

package livekit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ARequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A string `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B string `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	C int64  `protobuf:"varint,3,opt,name=c,proto3" json:"c,omitempty"`
}

func (x *ARequest) Reset() {
	*x = ARequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obfuscated_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ARequest) ProtoMessage() {}

func (x *ARequest) ProtoReflect() protoreflect.Message {
	mi := &file_obfuscated_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ARequest.ProtoReflect.Descriptor instead.
func (*ARequest) Descriptor() ([]byte, []int) {
	return file_obfuscated_proto_rawDescGZIP(), []int{0}
}

func (x *ARequest) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *ARequest) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

func (x *ARequest) GetC() int64 {
	if x != nil {
		return x.C
	}
	return 0
}

type AResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A string `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *AResponse) Reset() {
	*x = AResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obfuscated_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AResponse) ProtoMessage() {}

func (x *AResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obfuscated_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AResponse.ProtoReflect.Descriptor instead.
func (*AResponse) Descriptor() ([]byte, []int) {
	return file_obfuscated_proto_rawDescGZIP(), []int{1}
}

func (x *AResponse) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

type BRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A string `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B int64  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *BRequest) Reset() {
	*x = BRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obfuscated_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BRequest) ProtoMessage() {}

func (x *BRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obfuscated_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BRequest.ProtoReflect.Descriptor instead.
func (*BRequest) Descriptor() ([]byte, []int) {
	return file_obfuscated_proto_rawDescGZIP(), []int{2}
}

func (x *BRequest) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *BRequest) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type CRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A string `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *CRequest) Reset() {
	*x = CRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obfuscated_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRequest) ProtoMessage() {}

func (x *CRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obfuscated_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRequest.ProtoReflect.Descriptor instead.
func (*CRequest) Descriptor() ([]byte, []int) {
	return file_obfuscated_proto_rawDescGZIP(), []int{3}
}

func (x *CRequest) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

var File_obfuscated_proto protoreflect.FileDescriptor

var file_obfuscated_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6f, 0x62, 0x66, 0x75, 0x73, 0x63, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x6c, 0x69, 0x76, 0x65, 0x6b, 0x69, 0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x08, 0x41, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x62,
	0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x63, 0x22, 0x19,
	0x0a, 0x09, 0x41, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x61, 0x22, 0x26, 0x0a, 0x08, 0x42, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01,
	0x62, 0x22, 0x18, 0x0a, 0x08, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a,
	0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x61, 0x32, 0x98, 0x01, 0x0a, 0x0a,
	0x4f, 0x62, 0x66, 0x75, 0x73, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x01, 0x41, 0x12,
	0x11, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x6b, 0x69, 0x74, 0x2e, 0x41, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x6b, 0x69, 0x74, 0x2e, 0x41, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x01, 0x42, 0x12, 0x11, 0x2e, 0x6c, 0x69,
	0x76, 0x65, 0x6b, 0x69, 0x74, 0x2e, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2e, 0x0a, 0x01, 0x43, 0x12, 0x11, 0x2e, 0x6c, 0x69,
	0x76, 0x65, 0x6b, 0x69, 0x74, 0x2e, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x46, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x6b, 0x69, 0x74, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x6b, 0x69, 0x74, 0xaa, 0x02, 0x0d,
	0x4c, 0x69, 0x76, 0x65, 0x4b, 0x69, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0xea, 0x02, 0x0e,
	0x4c, 0x69, 0x76, 0x65, 0x4b, 0x69, 0x74, 0x3a, 0x3a, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_obfuscated_proto_rawDescOnce sync.Once
	file_obfuscated_proto_rawDescData = file_obfuscated_proto_rawDesc
)

func file_obfuscated_proto_rawDescGZIP() []byte {
	file_obfuscated_proto_rawDescOnce.Do(func() {
		file_obfuscated_proto_rawDescData = protoimpl.X.CompressGZIP(file_obfuscated_proto_rawDescData)
	})
	return file_obfuscated_proto_rawDescData
}

var file_obfuscated_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_obfuscated_proto_goTypes = []interface{}{
	(*ARequest)(nil),      // 0: livekit.ARequest
	(*AResponse)(nil),     // 1: livekit.AResponse
	(*BRequest)(nil),      // 2: livekit.BRequest
	(*CRequest)(nil),      // 3: livekit.CRequest
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_obfuscated_proto_depIdxs = []int32{
	0, // 0: livekit.Obfuscated.A:input_type -> livekit.ARequest
	2, // 1: livekit.Obfuscated.B:input_type -> livekit.BRequest
	3, // 2: livekit.Obfuscated.C:input_type -> livekit.CRequest
	1, // 3: livekit.Obfuscated.A:output_type -> livekit.AResponse
	4, // 4: livekit.Obfuscated.B:output_type -> google.protobuf.Empty
	4, // 5: livekit.Obfuscated.C:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_obfuscated_proto_init() }
func file_obfuscated_proto_init() {
	if File_obfuscated_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_obfuscated_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ARequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obfuscated_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obfuscated_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obfuscated_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_obfuscated_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_obfuscated_proto_goTypes,
		DependencyIndexes: file_obfuscated_proto_depIdxs,
		MessageInfos:      file_obfuscated_proto_msgTypes,
	}.Build()
	File_obfuscated_proto = out.File
	file_obfuscated_proto_rawDesc = nil
	file_obfuscated_proto_goTypes = nil
	file_obfuscated_proto_depIdxs = nil
}
